import {
  Blocks,
  BrickWall,
  CloudSun,
  Flower2,
  Grid2x2,
  LandPlot,
  Leaf,
  MountainSnow,
  PaintBucket,
  Scan,
  Sprout,
  Stamp,
  TreePine,
  Trees,
} from "lucide-react";
import type { Item } from "./types";

/**
 * Root item ID for the entities tree.
 */
export const rootItemId = "root";

/**
 * Indentation size for each tree level in pixels.
 */
export const indent = 20;

/**
 * Initially expanded items IDs.
 */
export const initialExpandedItems = [];

/**
 * Initially selected items IDs.
 */
export const initialSelectedItems = [];

/**
 * Normalized list of entities.
 */
export const initialItems: Record<string, Item> = {
  [rootItemId]: {
    // Root element is mandatory for tree component!
    name: "Root",
    parentID: null,
    children: ["weather", "terrain", "wall_1", "wall_2", "area", "spawn"],
    icon: <></>,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  weather: {
    name: "Weather",
    parentID: null,
    children: [],
    icon: <CloudSun />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  terrain: {
    name: "Terrain",
    children: [
      "paving_stone",
      "lava",
      "rock",
      "ground",
      "bricks",
      "chunks",
      "vegetation",
    ],
    parentID: null,
    icon: <MountainSnow />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  paving_stone: {
    name: "Paving Stone",
    parentID: "terrain",
    children: [],
    icon: <PaintBucket />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  lava: {
    name: "Lava",
    parentID: "terrain",
    children: [],
    icon: <PaintBucket />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  rock: {
    name: "Rock",
    parentID: "terrain",
    children: [],
    icon: <PaintBucket />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  ground: {
    name: "Ground",
    parentID: "terrain",
    children: [],
    icon: <PaintBucket />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  bricks: {
    name: "Bricks",
    parentID: "terrain",
    children: [],
    icon: <PaintBucket />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  chunks: {
    name: "Chunks",
    parentID: "terrain",
    children: ["chunk_0", "chunk_1", "chunk_2"],
    icon: <Grid2x2 />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  chunk_0: {
    name: "Chunk 0",
    parentID: "chunks",
    children: [],
    icon: <Blocks />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  chunk_1: {
    name: "Chunk 1",
    parentID: "chunks",
    children: [],
    icon: <Blocks />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  chunk_2: {
    name: "Chunk 2",
    parentID: "chunks",
    children: [],
    icon: <Blocks />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  vegetation: {
    name: "Vegetation",
    parentID: "terrain",
    children: ["grass", "plants"],
    icon: <Leaf />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  grass: {
    name: "Grass",
    parentID: "vegetation",
    children: ["grass_0", "grass_1", "flowers"],
    icon: <Sprout />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  grass_0: {
    name: "Grass 0",
    parentID: "grass",
    children: [],
    icon: <Sprout />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  grass_1: {
    name: "Grass 1",
    parentID: "grass",
    children: [],
    icon: <Sprout />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  flowers: {
    name: "Flowers",
    parentID: "grass",
    children: ["petunia"],
    icon: <Flower2 />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  petunia: {
    name: "Petunia",
    parentID: "flowers",
    children: [],
    icon: <Flower2 />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  plants: {
    name: "Plants",
    parentID: "grass",
    children: ["tree_0", "tree_1"],
    icon: <Trees />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  tree_0: {
    name: "Tree 0",
    parentID: "plants",
    children: [],
    icon: <TreePine />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  tree_1: {
    name: "Tree 1",
    parentID: "plants",
    children: [],
    icon: <TreePine />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  wall_1: {
    name: "Wall 1",
    parentID: "null",
    children: [],
    icon: <BrickWall />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  wall_2: {
    name: "Wall 2",
    parentID: "null",
    children: [],
    icon: <BrickWall />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  area: {
    name: "Area",
    parentID: "null",
    children: ["decal"],
    icon: <Scan />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  decal: {
    name: "Danger",
    parentID: "area",
    children: [],
    icon: <Stamp />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
  spawn: {
    name: "Spawn point",
    parentID: null,
    children: [],
    icon: <LandPlot />,
    iconColor: "",
    isVisible: true,
    isLocked: false,
    tagID: null,
  },
};
